title: "Climate Change & Impacts @ UQAM"
description: "Research group studying climate–land–water interactions in a warming world."
url: "https://coreylesk.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.26.0"
plugins:
  - jekyll-remote-theme # only needed if using remote_theme

# Build settings
plugins:
  - jekyll-include-cache

# Author info (optional)
author:
  name: "Corey Lesk"
  avatar: "/images/corey.jpg"
  bio: "Assistant Professor researching climate–land–water interactions."
  email: "lesk.corey [at] uqam [dot] ca"

# Navigation
collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

navigation: navigation.yml

header:
  font-family: "Helvetica, Arial, sans-serif;"  # Change this to the font you prefer (e.g., "Open Sans", "Lora", etc.)


body:
  font-family: "Helvetica, Arial, sans-serif;"  # Change this to your desired body font